# Generated by Django 6.0.7 on 2026-07-13 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_user_to_existing_notes(apps, schema_editor):
    Note = apps.get_model('notes', 'Note')
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(app_label, model_name)

    user = User.objects.order_by('id').first()
    if user is None:
        user = User.objects.create(username='migration_owner')

    Note.objects.filter(user__isnull=True).update(user_id=user.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(assign_user_to_existing_notes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
